# Generated by Django 6.1 on 2026-09-09 10:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='category',
            field=models.CharField(choices=[('organization', 'Organization'), ('committee', 'Committee'), ('volunteer', 'Volunteer'), ('training', 'Training & Workshop'), ('internship', 'Internship')], default='Organization', max_length=20),
        ),
    ]
